### ISSUE TITLE
obj model doesn't appear

### ISSUE THREAD

**Issue by cwule** [janus3D/janus3D_toolbox#4]
I was very excited about the paper and would like to try janus3D, unfortunately I cannot even get started by loading obj files.
While it says loading and done and there are no error messages in Matlab, no model shows up on the screen. 
The obj file has ~250k vertices, I can open it eg. in meshlab or blender without problems.
The nii also doesn't load (stuck in loading, never changes to done).
I am using Matlab2016b. The image processing, CV and fieldtrip toolboxes are installed.
I followed this guide: https://janus3d.github.io/janus3D_toolbox/

**Comment by TommyClausner** [comment]
Hey @cwule ,

Thanks for the interest in janus3D! The main problem with the toolbox is, that - as far as I know - it only runs (correctly) on MatlabR2015a. This is due to the fact, that in later versions the internal graphics API changed and I haven't been able to make the required adjustments yet. 

However in your case I think the problem could maybe be even more trivial: When loading the '.obj' file, the model will not show up on it's own. 

If you do not see the model when 'positioning' the model (after loading), then the problem is indeed caused by the MatLab version I'm afraid. Is the model correctly displayed in the 'positioning view' (Model -> position model)?

Best, 
Tommy

**Comment by cwule** [comment]
Thanks for the feedback! The issue was the format of the obj-file. My file contained also color and vertex normal information. After removing these, the obj loaded without problems.

**Comment by TommyClausner** [comment]
Thanks @cwule for the info!
